CDEBUG = -g -Wall
LDEBUG = -g

LIBS = \
-lCTclApp -lCWebGet -lCThread -lCHtml -lCFile -lCEnv \
-lCImageLib -lCHttp -lCTcp -lCOS -lCGlob -lCUtil -lCStrUtil \
-lCFileUtil -lCOS -lCRegExp -lCUrl -lCReadLine -lCHistory \
-lCOSFile -lCPrintF -lCStrNCase \
-lpthread -lpng -ljpeg \
-lreadline -lcurses -ltix -ltk -ltcl -lXt -lX11 -lXext -lmy_regexp

PROG    = CTclWebGet
CPP_SRC = CTclWebGet.cpp

TCL_FILES = CTclWebGet.tcl

include $(MAKE_DIR)/bin.mk
