#ifndef CHtmlTypes_H
#define CHtmlTypes_H

#include <vector>

enum CHtmlTagId {
  CHTML_TAG_ID_NONE,
  CHTML_TAG_ID_A,
  CHTML_TAG_ID_ADDRESS,
  CHTML_TAG_ID_APPLET,
  CHTML_TAG_ID_AREA,
  CHTML_TAG_ID_B,
  CHTML_TAG_ID_BASE,
  CHTML_TAG_ID_BASEFONT,
  CHTML_TAG_ID_BGSOUND,
  CHTML_TAG_ID_BIG,
  CHTML_TAG_ID_BLINK,
  CHTML_TAG_ID_BLOCKQUOTE,
  CHTML_TAG_ID_BODY,
  CHTML_TAG_ID_BR,
  CHTML_TAG_ID_CAPTION,
  CHTML_TAG_ID_CENTER,
  CHTML_TAG_ID_CITE,
  CHTML_TAG_ID_CODE,
  CHTML_TAG_ID_DD,
  CHTML_TAG_ID_DFN,
  CHTML_TAG_ID_DIR,
  CHTML_TAG_ID_DIV,
  CHTML_TAG_ID_DL,
  CHTML_TAG_ID_DT,
  CHTML_TAG_ID_EM,
  CHTML_TAG_ID_FONT,
  CHTML_TAG_ID_FORM,
  CHTML_TAG_ID_FRAME,
  CHTML_TAG_ID_FRAMESET,
  CHTML_TAG_ID_H1,
  CHTML_TAG_ID_H2,
  CHTML_TAG_ID_H3,
  CHTML_TAG_ID_H4,
  CHTML_TAG_ID_H5,
  CHTML_TAG_ID_H6,
  CHTML_TAG_ID_HEAD,
  CHTML_TAG_ID_HR,
  CHTML_TAG_ID_HTML,
  CHTML_TAG_ID_I,
  CHTML_TAG_ID_IMG,
  CHTML_TAG_ID_INPUT,
  CHTML_TAG_ID_ISINDEX,
  CHTML_TAG_ID_KBD,
  CHTML_TAG_ID_LI,
  CHTML_TAG_ID_LINK,
  CHTML_TAG_ID_LISTING,
  CHTML_TAG_ID_MAP,
  CHTML_TAG_ID_MARQUEE,
  CHTML_TAG_ID_MENU,
  CHTML_TAG_ID_META,
  CHTML_TAG_ID_NEXTID,
  CHTML_TAG_ID_NOBR,
  CHTML_TAG_ID_NOFRAMES,
  CHTML_TAG_ID_NOSCRIPT,
  CHTML_TAG_ID_OL,
  CHTML_TAG_ID_OPTION,
  CHTML_TAG_ID_P,
  CHTML_TAG_ID_PARAM,
  CHTML_TAG_ID_PLAINTEXT,
  CHTML_TAG_ID_PRE,
  CHTML_TAG_ID_S,
  CHTML_TAG_ID_SAMP,
  CHTML_TAG_ID_SCRIPT,
  CHTML_TAG_ID_SELECT,
  CHTML_TAG_ID_SMALL,
  CHTML_TAG_ID_SPAN,
  CHTML_TAG_ID_STRIKE,
  CHTML_TAG_ID_STRONG,
  CHTML_TAG_ID_STYLE,
  CHTML_TAG_ID_SUB,
  CHTML_TAG_ID_SUP,
  CHTML_TAG_ID_TABLE,
  CHTML_TAG_ID_TD,
  CHTML_TAG_ID_TEXTAREA,
  CHTML_TAG_ID_TH,
  CHTML_TAG_ID_TITLE,
  CHTML_TAG_ID_TR,
  CHTML_TAG_ID_TT,
  CHTML_TAG_ID_U,
  CHTML_TAG_ID_UL,
  CHTML_TAG_ID_VAR,
  CHTML_TAG_ID_WBR,
  CHTML_TAG_ID_XMP,
  CHTML_TAG_ID_COMMENT,
};

enum CHtmlTextType {
  CHTML_TEXT_TYPE_NONE,
  CHTML_TEXT_TYPE_PLAIN,
  CHTML_TEXT_TYPE_STYLE,
  CHTML_TEXT_TYPE_LITERAL,
  CHTML_TEXT_TYPE_RAW,
};

class CHtmlParserTokens;
class CHtmlParser;
class CHtmlNamedChar;
class CHtmlTagDef;
class CHtmlTagOption;
class CHtmlToken;

typedef std::vector<CHtmlToken *>     CHtmlTokenArray;
typedef std::vector<CHtmlTagOption *> CHtmlTagOptionArray;

#endif
